import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

import { store } from "@/redux/store";
import ReduxProvider from "@/providers/ReduxProvider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider store={store}>
          <Toaster
            position="bottom-center"
            reverseOrder={false}
            toastOptions={{
              style: {
                fontFamily: "var(--font-uni)",
                background: "#333",
                color: "#fff",
              },
              iconTheme: {
                primary: "#ffffff",
                secondary: "#333",
              },
            }}
          />

          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
